//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pinturería_Acuarela
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.Product_Business = new HashSet<Product_Business>();
            this.Product_Order = new HashSet<Product_Order>();
        }
    
        public int id { get; set; }
        public string description { get; set; }
        public int id_brand { get; set; }
        public Nullable<int> id_category { get; set; }
        public Nullable<int> id_subcategory { get; set; }
        public Nullable<int> id_capacity { get; set; }
        public Nullable<int> id_color { get; set; }
        public int quantity { get; set; }
        public int internal_code { get; set; }
        public System.DateTime created_at { get; set; }
        public Nullable<System.DateTime> deleted_at { get; set; }
    
        public virtual Brand Brand { get; set; }
        public virtual Capacity Capacity { get; set; }
        public virtual Category Category { get; set; }
        public virtual Color Color { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product_Business> Product_Business { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product_Order> Product_Order { get; set; }
        public virtual Subcategory Subcategory { get; set; }
    }
}
