//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pinturería_Acuarela
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Product_Order
    {
        public int id_product { get; set; }
        public long id_order { get; set; }

        [Required(ErrorMessage = "Debes agregar una cantidad")]
        [Range(1, 10000, ErrorMessage = "Debes seleccionar una cantidad entre 1 y  10.000")]
        public int quantity { get; set; }
        public bool status { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual Product Product { get; set; }
    }
}
