//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pinturería_Acuarela
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.Order = new HashSet<Order>();
        }
    
        public int id { get; set; }

        [Required(ErrorMessage = "Debes agregar un email")]
        [StringLength(50, ErrorMessage = "Debes añadir un email de menos de 50 caracteres")]
        [EmailAddress(ErrorMessage = "Debes ingresar un formato de email válido")]
        public string email { get; set; }

        [Required(ErrorMessage = "Debes ingresar una contraseña")]
        [DataType(DataType.Password, ErrorMessage = "Ingrese una contraseña válida")]
        public string password { get; set; }

        [Required(ErrorMessage = "Debes agregar un rol")]
        public short id_rol { get; set; }
        public Nullable<int> id_business { get; set; }
    
        public virtual Business Business { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Order { get; set; }
        public virtual Rol Rol { get; set; }
    }
}
